stages:
  - deploy

deploy:
  stage: deploy
  image: docker.siemens.com/ccp/vm:stable
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq cf-cli
    - mkdir -p ~/.cf
    - echo "{\"ConfigVersion\":3,\"Target\":\"$CF_API\",\"AccessToken\":\"bearer ${CF_ACCESS_TOKEN}\",\"RefreshToken\":\"${CF_REFRESH_TOKEN}\"}" > ~/.cf/config.json
    - cf target -o $CF_ORG -s $CF_SPACE
    - cf push
